### ISSUE TITLE
[Question] how do you .html file type?

### ISSUE THREAD

**Issue by delgermurun** [Slava/vim-spacebars#1]
Meteor only detect html files (I guess), so how do can I tell to vim it is spacebar file? How do you solve this issue?

Thank you.

**Comment by Slava** [comment]
``` viml
if has("autocmd")
  au  BufNewFile,BufRead *.html,*.spacebars,*.mustache,*.handlebars,*.hbs,*.hogan,*.hulk,*.hjs set filetype=html syntax=spacebars | runtime! ftplugin/spacebars.vim ftplugin/spacebars*.vim ftplugin/spacebars/*.vim
endif
```

This is already part of the plugin but if it didn't work, some other plugin might overwrite it. In that case jsut copy this code to the end of your `.vimrc`.

**Comment by delgermurun** [comment]
It works. Thank you.

**Comment by george-carlin** [comment]
I had to change the above snippet to say **`filetype=spacebars`** instead of `filetype=html` to get it work. Not sure if this will have negative consequences elsewhere, but it works with my meteor project(s) at least.
